name: activeuf
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - transformers=4.51.3
  - tokenizers=0.21.1
  - tiktoken=0.9.0
  - datasets=3.4.1
  - openai=1.70.0
  - numpy=1.26.4
  - pandas=2.2.3
  - tqdm=4.67.1
  - nvitop
  - pip:
    - deepspeed==0.16.5
    - accelerate==1.6.0
    - vllm
    - git+https://github.com/allenai/reward-bench.git
    - bitsandbytes
    - peft
    - dotenv==0.9.9
    - mmh3
    - tensordict
    - langdetect
    - nltk
    - immutabledict
