name: ultrafeedback
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - transformers
  - tokenizers
  - datasets
  - openai
  - numpy
  - pandas
  - tqdm
  - pip
  - pip:
    - deepspeed
    - accelerate
    - vllm
