debug: false

seed: 42
torch_dtype: bfloat16

train_path: datasets/preference_ultrafeedback_llama
model_path: allenai/Llama-3.1-Tulu-3-8B-SFT
base_run_name: llama_8b-normed-preference_ultrafeedback_llama
base_output_dir: trainer_output/dpo/

lora:
  r: 64
  lora_alpha: 128
  lora_dropout: 0.05
  bias: none
  task_type: CAUSAL_LM

training:
  gradient_checkpointing: true
  gradient_checkpointing_kwargs:
    use_reentrant: false
  max_length: 2048
  per_device_train_batch_size: 1
  gradient_accumulation_steps: 16
  learning_rate: 5.0e-7
  lr_scheduler_type: linear
  warmup_ratio: 0.1
  num_train_epochs: 3
  report_to: wandb
  logging_steps: 1
  beta: 5
  save_steps: 200
  normalize_logps: true