general:
  base_model: allenai/Llama-3.1-Tulu-3-8B-SFT
  seed: 42
  torch_dtype: bfloat16

lora:
  r: 16
  lora_alpha: 32
  lora_dropout: 0.05
  bias: none
  task_type: SEQ_CLS
  target_module_patterns: ["query", "key", "value"]

training:
  train_batch_size: 32
  eval_batch_size: 32
  epochs: 2
  grad_acc_steps: 2
  logging_steps: 10
  save_strategy: "no"
  save_steps: 500
  remove_unused_columns: false
  max_length: 4096
  report_to: "wandb"
  max_steps: -1
  bf16: true
  lr_scheduler_type: constant

optimization:
  optimizer: adamw_torch
  learning_rate: 5e-6

lr_scheduling:
  num_warmup_steps: 0
